name: Backblaze B2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Backblaze B2
        uses: backblaze/b2-action@v1
        env:
          B2_BUCKET_ID: ffde385a97b0ca039e5c0814
          B2_APPLICATION_KEY_ID: fe8a70a3ec84
          B2_APPLICATION_KEY: 0058edd76d9d4044ff76e98bbea8630fc89ea7833f

      - name: Deploy to Backblaze B2
        run: |
          b2 sync ./ ffde385a97b0ca039e5c0814
